sonar.projectKey=senegaladmin
sonar.projectName=SénégalAdmin
sonar.projectVersion=1.0

# Backend Laravel
sonar.sources=suivi_extrait/app,suivi_extrait/routes
sonar.exclusions=suivi_extrait/vendor/**,suivi_extrait/node_modules/**

# Frontend Angular
sonar.javascript.lcov.reportPaths=suivi_estrait-frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.language=php